---
# tasks file for payarai

  - name: Create Payara group
    group: name=payara state=present

  - name: Create Payara user
    user: name=payara group=payara comment="The Payara server user" home={{ install_folder }}/payara/ createhome=no state=present

  - name: Install EPEL
    yum: name=epel-release state=present

  - name: install dependencies
    yum: name={{ item }} state=latest
    with_items: dependencies

  - name: install zip / unzip
    yum: name=unzip state=present

  - name: Download latest Payara release to /tmp
    get_url: url={{ payara_download_url }} dest=/tmp/payara.zip

  - name: Unzip to {{ install_folder }}
    unarchive: src=/tmp/payara.zip dest={{ install_folder }} copy=no

  - name: Link payara to payara41
    file: src={{ install_folder }}/payara41 dest={{ install_folder }}/payara state=link owner=payara group=payara

  - name: Create password-change.txt
    template: src=password-change.txt.j2 dest=/tmp/password-change.txt owner=payara group=payara mode=0600

  - name: Create password.txt
    template: src=password.txt.j2 dest=/tmp/password.txt owner=payara group=payara mode=0600

  - name: delete domain1
    command: "{{ install_folder }}/payara/bin/asadmin delete-domain domain1"

  - name: Set password for asadmin
    command: "{{ install_folder }}/payara/bin/asadmin --user admin --passwordfile /tmp/password-change.txt change-admin-password"

  - name: set ownership to payara
    file: path={{ install_folder }}/payara41 recurse=yes owner=payara group=payara

  - name: create systemd wrapper for Payara
    copy: src=payara.service dest=/usr/lib/systemd/system/payara.service

  - name: start Payara and add as default service
    service: name=payara state=started enabled=yes

  - name: Enable "remote" admin
    command: "{{ install_folder }}/payara/bin/asadmin --user admin --passwordfile /tmp/password.txt enable-secure-admin"

  - name: Remove -client jvm option
    command: "{{ install_folder }}/payara/bin/asadmin --user admin --passwordfile /tmp/password.txt delete-jvm-options -client"

  - name: Remove -Xmx512m jvm option
    command: "{{ install_folder }}/payara/bin/asadmin --user admin --passwordfile /tmp/password.txt delete-jvm-options -Xmx512m"

  - name: Set jvm_options
    command: "{{ install_folder }}/payara/bin/asadmin --user admin --passwordfile /tmp/password.txt create-jvm-options {{ item }}"
    with_items: jvm_options

  - name: Restart to enable new settings
    service: name=payara state=restarted

  - name: Clean up install package
    file: path=/tmp/payara.zip state=absent
