---
# tasks file for payara

- name: ensure server is ready
  include: prepare.yml

- name: setup user and service
  include: user.yml

- name: ensure payara can be started as a service
  include: service.yml

- name: setup payara
  include: install.yml

